<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Alert, AlertDialog, Badge, Button, Card, Checkbox, Drawer, EmptyState, Input, PageHeader, PrintPreview, Select, Tabs, Textarea, TriangleAlertIcon, TruckIcon, sanitizeRichText, type SelectOption, type TabItem } from '@thiagoschoeffel/ts-components'
import type { AuthenticatedApiRequest } from '../services/ordersApi'
import { cancelRoute, createRoute, getLogistics, recordAttempt, rescheduleDelivery, shortLogisticsId, startRoute, type DeliveryAttemptResult, type DeliveryRoute, type DeliveryStop, type LogisticsSnapshot } from '../services/logisticsApi'

const props = defineProps<{ apiRequest?: AuthenticatedApiRequest }>()
const window = globalThis.window
type Tab = 'planning' | 'in-progress' | 'completed'
const tabs: TabItem[] = [{ value: 'planning', label: 'Planejamento' }, { value: 'in-progress', label: 'Em rota' }, { value: 'completed', label: 'Concluídas' }]
const snapshot = ref<LogisticsSnapshot>({ drivers: [], availableOrders: [], routes: [], reschedules: [] })
const activeTab = ref<Tab>('planning'); const loading = ref(true); const error = ref(''); const feedback = ref('')
const routeDrawer = ref(false); const selectedDriverId = ref(''); const selectedWindow = ref(''); const selectedOrders = ref<string[]>([]); const saving = ref(false)
const attemptDrawer = ref(false); const activeRoute = ref<DeliveryRoute>(); const activeStop = ref<DeliveryStop>(); const attemptResult = ref<DeliveryAttemptResult>('Succeeded'); const failureReason = ref(''); const note = ref(''); const receivedBy = ref('')
const rescheduleDrawer = ref(false); const rescheduleDate = ref(''); const rescheduleWindow = ref(''); const rescheduleReason = ref('')
const printOpen = ref(false); const printRoute = ref<DeliveryRoute>()
const cancelConfirmationOpen = ref(false); const cancelCandidate = ref<DeliveryRoute>()
const activeDrivers = computed(() => snapshot.value.drivers.filter(x => x.isActive && x.isAvailable))
const driverOptions = computed<SelectOption[]>(() => activeDrivers.value.map(x => ({ value: x.id, label: x.name, description: x.phone ?? x.identification })))
const windowOptions = computed<SelectOption[]>(() => [...new Set(snapshot.value.availableOrders.map(x => x.deliveryWindow))].sort().map(value => ({ value, label: value })))
const eligibleOrders = computed(() => snapshot.value.availableOrders.filter(x => x.deliveryWindow === selectedWindow.value))
const visibleRoutes = computed(() => snapshot.value.routes.filter(route => activeTab.value === 'planning' ? route.status === 'Planned' : activeTab.value === 'in-progress' ? route.status === 'InProgress' : ['Completed', 'Cancelled'].includes(route.status)))
const counts = computed(() => ({ planning: snapshot.value.routes.filter(x => x.status === 'Planned').length, 'in-progress': snapshot.value.routes.filter(x => x.status === 'InProgress').length, completed: snapshot.value.routes.filter(x => ['Completed', 'Cancelled'].includes(x.status)).length }))
const failureOptions: SelectOption[] = ['Cliente ausente', 'Endereço incorreto', 'Acesso impedido', 'Cliente sem resposta', 'Outro motivo operacional'].map(value => ({ value, label: value }))

async function load() { if (!props.apiRequest) { error.value = 'A sessão autenticada da API não está disponível.'; loading.value = false; return } loading.value = true; error.value = ''; try { snapshot.value = await getLogistics(props.apiRequest) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível carregar as entregas.' } finally { loading.value = false } }
function openNewRoute() { selectedDriverId.value = ''; selectedWindow.value = ''; selectedOrders.value = []; routeDrawer.value = true }
function toggleOrder(id: string, value: boolean | 'indeterminate') { selectedOrders.value = value === true ? [...selectedOrders.value, id] : selectedOrders.value.filter(x => x !== id) }
async function saveRoute(close: () => void) { if (!props.apiRequest || !selectedDriverId.value || !selectedWindow.value || !selectedOrders.value.length) return; saving.value = true; try { await createRoute(props.apiRequest, { date: eligibleOrders.value[0]!.date, deliveryWindow: selectedWindow.value, driverId: selectedDriverId.value, orderIds: selectedOrders.value }); feedback.value = 'Rota criada com sucesso.'; close(); await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível criar a rota.' } finally { saving.value = false } }
async function begin(route: DeliveryRoute) { if (!props.apiRequest) return; try { await startRoute(props.apiRequest, route); feedback.value = `Rota #${shortLogisticsId(route.id)} iniciada.`; activeTab.value = 'in-progress'; await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível iniciar a rota.' } }
async function performCancel(route: DeliveryRoute) { if (!props.apiRequest) return; try { await cancelRoute(props.apiRequest, route); feedback.value = 'Rota cancelada e pedidos liberados para novo planejamento.'; await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível cancelar a rota.' } }
function cancel(route: DeliveryRoute) { cancelCandidate.value = route; cancelConfirmationOpen.value = true }
async function confirmCancel() { if (cancelCandidate.value) await performCancel(cancelCandidate.value); cancelCandidate.value = undefined }
function openAttempt(route: DeliveryRoute, stop: DeliveryStop, result: DeliveryAttemptResult) { activeRoute.value = route; activeStop.value = stop; attemptResult.value = result; failureReason.value = ''; note.value = ''; receivedBy.value = ''; attemptDrawer.value = true }
async function saveAttempt(close: () => void) { if (!props.apiRequest || !activeRoute.value || !activeStop.value || attemptResult.value === 'Failed' && !failureReason.value) return; saving.value = true; try { await recordAttempt(props.apiRequest, activeRoute.value, activeStop.value, attemptResult.value, failureReason.value || undefined, sanitizeRichText(note.value), receivedBy.value || undefined); feedback.value = attemptResult.value === 'Succeeded' ? 'Entrega concluída.' : 'Falha registrada sem apagar o histórico.'; close(); await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível registrar a tentativa.' } finally { saving.value = false } }
function openReschedule(route: DeliveryRoute, stop: DeliveryStop) { activeRoute.value = route; activeStop.value = stop; rescheduleDate.value = ''; rescheduleWindow.value = route.deliveryWindow; rescheduleReason.value = ''; rescheduleDrawer.value = true }
async function saveReschedule(close: () => void) { if (!props.apiRequest || !activeStop.value || !rescheduleDate.value || !rescheduleWindow.value || !rescheduleReason.value) return; saving.value = true; try { await rescheduleDelivery(props.apiRequest, activeStop.value.orderId, rescheduleDate.value, rescheduleWindow.value, rescheduleReason.value); feedback.value = 'Entrega reagendada e disponível para uma nova rota.'; close(); activeTab.value = 'planning'; await load() } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Não foi possível reagendar.' } finally { saving.value = false } }
function showPrint(route: DeliveryRoute) { printRoute.value = route; printOpen.value = true }
function printSheet() { window.print() }
function status(route: DeliveryRoute) { return route.status === 'Planned' ? ['Planejada', 'neutral'] as const : route.status === 'InProgress' ? ['Em rota', 'info'] as const : route.status === 'Completed' ? ['Concluída', 'success'] as const : ['Cancelada', 'danger'] as const }
onMounted(load)
</script>

<template>
  <section class="md:flex md:h-full md:min-h-0 md:flex-col" aria-label="Entregas">
    <div class="ts-responsive-row gap-4">
      <PageHeader title="Entregas" subtitle="Planeje rotas e acompanhe cada pedido até a confirmação da entrega."><template #icon><TruckIcon :size="32" :stroke-width="1.75" /></template></PageHeader>
      <Button v-if="activeTab === 'planning'" @click="openNewRoute">Nova rota</Button>
    </div>
    <Alert v-if="feedback" class="mt-4" variants="success" :description="feedback" />
    <Alert v-if="error" class="mt-4" variants="danger" title="Não foi possível concluir a operação" :description="error"><template #icon><TriangleAlertIcon /></template><template #action><Button size="small" variant="secondary" @click="load">Tentar novamente</Button></template></Alert>
    <Card class="mt-6 md:min-h-0 md:flex-1 [&>div]:flex [&>div]:min-h-0 [&>div]:flex-col [&>div]:p-4">
      <Tabs v-model="activeTab" :tabs="tabs" aria-label="Etapas da logística"><template #badge="{ tab }"><Badge size="small" variant="neutral">{{ counts[tab.value as Tab] }}</Badge></template></Tabs>
      <div v-if="loading" class="mt-4 grid gap-4 lg:grid-cols-2"><div v-for="i in 4" :key="i" class="h-44 animate-pulse rounded-lg border border-slate-200 bg-slate-50" /></div>
      <EmptyState v-else-if="!visibleRoutes.length" class="mt-4" :title="activeTab === 'planning' ? 'Nenhuma rota planejada' : activeTab === 'in-progress' ? 'Nenhuma rota em andamento' : 'Nenhuma rota concluída'" :description="activeTab === 'planning' ? `${snapshot.availableOrders.length} pedidos estão disponíveis para planejamento.` : 'As rotas aparecerão aqui conforme forem executadas.'"><template #icon><TruckIcon /></template><template #action><Button v-if="activeTab === 'planning' && snapshot.availableOrders.length" size="small" @click="openNewRoute">Criar rota</Button></template></EmptyState>
      <div v-else class="mt-4 grid min-h-0 gap-4 overflow-auto lg:grid-cols-2">
        <Card v-for="route in visibleRoutes" :key="route.id">
          <template #header><div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold text-slate-900">Rota #{{ shortLogisticsId(route.id) }}</h2><p class="mt-1 text-sm text-slate-500">{{ route.driverName }} · {{ route.deliveryWindow }}</p></div><Badge :variant="status(route)[1]">{{ status(route)[0] }}</Badge></div></template>
          <ol class="divide-y divide-slate-100"><li v-for="stop in route.stops" :key="stop.id" class="py-3 first:pt-0 last:pb-0"><div class="flex items-start justify-between gap-3"><div><p class="font-medium text-slate-800">{{ stop.position }}. {{ stop.customerName }}</p><p class="mt-1 text-xs text-slate-500">{{ stop.address }} · {{ stop.customerPhone || 'Sem telefone' }}</p></div><Badge v-if="stop.result" :variant="stop.result === 'Succeeded' ? 'success' : 'danger'">{{ stop.result === 'Succeeded' ? 'Entregue' : 'Falha' }}</Badge></div><div v-if="route.status === 'InProgress' && !stop.result" class="mt-3 flex flex-wrap gap-2"><Button size="small" variant="success" @click="openAttempt(route, stop, 'Succeeded')">Marcar entregue</Button><Button size="small" variant="secondary" @click="openAttempt(route, stop, 'Failed')">Registrar falha</Button></div><Button v-if="route.status === 'Completed' && stop.result === 'Failed' && !snapshot.reschedules.some(x => x.orderId === stop.orderId)" class="mt-3" size="small" variant="secondary" @click="openReschedule(route, stop)">Reagendar</Button></li></ol>
          <template #footer><div class="flex flex-wrap justify-end gap-2"><Button size="small" variant="secondary" @click="showPrint(route)">Folha de rota</Button><Button v-if="route.status === 'Planned'" size="small" variant="danger" @click="cancel(route)">Cancelar</Button><Button v-if="route.status === 'Planned'" size="small" variant="success" @click="begin(route)">Iniciar rota</Button></div></template>
        </Card>
      </div>
    </Card>
  </section>

  <Drawer v-model:open="routeDrawer" title="Nova rota" description="Escolha uma janela, um entregador disponível e ordene as paradas."><template #default="{ close }"><div class="space-y-4"><Select v-model="selectedWindow" label="Janela" :options="windowOptions" /><Select v-model="selectedDriverId" label="Entregador" :options="driverOptions" /><div v-if="selectedWindow" class="space-y-2"><Card v-for="order in eligibleOrders" :key="order.id"><Checkbox :model-value="selectedOrders.includes(order.id)" :label="order.customerName" @update:model-value="toggleOrder(order.id, $event)" /><p class="mt-2 text-xs text-slate-500">#{{ shortLogisticsId(order.id) }} · {{ order.address }}</p><Badge v-if="order.preferredDriverId === selectedDriverId" class="mt-2" variant="info">Preferência do cliente</Badge></Card></div><EmptyState v-else size="small" title="Selecione uma janela" description="Os pedidos aptos aparecerão aqui." /></div><div class="mt-6 flex justify-end gap-2"><Button variant="secondary" @click="close">Cancelar</Button><Button :loading="saving" :disabled="!selectedOrders.length || !selectedDriverId" @click="saveRoute(close)">Criar rota</Button></div></template></Drawer>
  <Drawer v-model:open="attemptDrawer" :title="attemptResult === 'Succeeded' ? 'Concluir entrega' : 'Registrar falha'" description="A tentativa permanecerá no histórico do pedido."><template #default="{ close }"><div class="space-y-4"><Select v-if="attemptResult === 'Failed'" v-model="failureReason" label="Motivo" :options="failureOptions" required /><Input v-else v-model="receivedBy" label="Quem recebeu (opcional)" /><Textarea v-model="note" rich-text label="Observação (opcional)" /></div><div class="mt-6 flex justify-end gap-2"><Button variant="secondary" @click="close">Cancelar</Button><Button :loading="saving" @click="saveAttempt(close)">Registrar tentativa</Button></div></template></Drawer>
  <Drawer v-model:open="rescheduleDrawer" title="Reagendar entrega" description="A tentativa anterior continuará visível no histórico."><template #default="{ close }"><div class="space-y-4"><Input v-model="rescheduleDate" type="date" label="Nova data" /><Input v-model="rescheduleWindow" label="Nova janela" /><Textarea v-model="rescheduleReason" rich-text label="Motivo" required /></div><div class="mt-6 flex justify-end gap-2"><Button variant="secondary" @click="close">Cancelar</Button><Button :loading="saving" @click="saveReschedule(close)">Reagendar</Button></div></template></Drawer>
  <PrintPreview v-model:open="printOpen" title="Folha de rota" @print="window.print()"><article v-if="printRoute" class="space-y-5 bg-white p-6 text-slate-900"><header><p class="text-sm">Sabor Santè</p><h2 class="text-2xl font-bold">Rota #{{ shortLogisticsId(printRoute.id) }}</h2></header><dl class="grid grid-cols-2 gap-3 text-sm"><div><dt class="text-slate-500">Entregador</dt><dd class="font-semibold">{{ printRoute.driverName }}</dd></div><div><dt class="text-slate-500">Janela</dt><dd class="font-semibold">{{ printRoute.deliveryWindow }}</dd></div></dl><ol class="divide-y divide-slate-300 border-y border-slate-400"><li v-for="stop in printRoute.stops" :key="stop.id" class="py-4"><strong>{{ stop.position }}. {{ stop.customerName }}</strong><p>{{ stop.address }}</p><p>{{ stop.customerPhone }}</p><p class="mt-2">□ Entregue &nbsp; □ Falha &nbsp; Horário: ____:____</p></li></ol><p class="border-t border-slate-500 pt-2">Assinatura do entregador</p></article></PrintPreview>
  <AlertDialog v-model:open="cancelConfirmationOpen" title="Cancelar rota?" description="Os pedidos voltarão ao planejamento e o registro da rota cancelada será preservado." cancel-label="Manter rota" confirm-label="Cancelar rota" confirm-variant="danger" @confirm="confirmCancel" />
</template>
